MACGYVER = 'M'
MACGYVER_IMG = 'macgyver.png'
MURDOC = 'G'
MURDOC_IMG = 'murdoc.png'
WALL = '#'
WALL_IMG = 'wall.png'
FLOOR = ' '
FLOOR_IMG = 'grass.png'
NEEDLE = 'N'
NEEDLE_IMG = 'needle.png'
TUBE = 'T'
TUBE_IMG = 'tube.png'
ETHER = 'E'
ETHER_IMG = 'ether.png'
EMPTY = ' '
YES = 'o'
UP = 'z'
DOWN = 's'
LEFT = 'q'
RIGHT = 'd'
LEAVE = 'l'
WINDOW_SIZE = (480, 480)
ICON_IMG = 'icon.png'
TITLE = "MURDOC'S MAZE"
SPRITE_SIZE = 32
WIN = 'WON'
WIN_SIZ = 100
WIN_WRI = "YOU WIN !!!"
WIN_COL = 255, 255, 0
WIN_LOC = 45, 210
LOOSE = 'LOSE'
LOS_SIZ = 100
LOS_WRI = "GAME OVER"
LOS_COL = 255, 0, 0
LOS_LOC = 31, 210
COUNT_SIZ = 38
COUNT_COL = 35, 0, 0
COUNT_LOC = 205, 5
SY_SIZ = 35
SY_WRI = "Sleep syringe has been made"
SY_COL = 255, 255, 51
SY_LOC = 5, 454
